import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { entregas_pages } from "./entregas.pages.ts";
import { entregas_tables } from "./entregas.tables.ts";

export const entregas_module = define_module({
  resource: "entregas",
  labels: {
    singular: "Cola chofer (carga/entrega)",
    plural: "Cola chofer (carga/entrega)",
    read: "Ver Cola chofer (carga/entrega)",
    write: "Editar Cola chofer (carga/entrega)",
  },
  routes: define_crud({
    resource: "entregas",
    table: "entregas",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "entregas",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      pedido: { type: "string", search: true },
      pedido_folio: { type: "string", search: true },
      pedido_folio_interno: { type: "number" },
      pedido_contacto_nombre: { type: "string", search: true },
      pedido_contacto_domicilio: { type: "string", search: true },
      pedido_contacto_url_maps: { type: "string", search: true },
      delivery_route: { type: "string", search: true },
      delivery_route_nombre: { type: "string", search: true },
      vehicle: { type: "string", search: true },
      vehicle_nombre: { type: "string", search: true },
      codigo_bulto: { type: "string", search: true },
      numero_bulto: { type: "number" },
      peso_kg: { type: "number" },
      contenido_resumen: { type: "string", search: true },
      pedido_total_bultos: { type: "number" },
      estado: { type: "string", search: true },
      latitude: { type: "number" },
      longitude: { type: "number" },
      event_id: { type: "string", search: true },
      event_type: { type: "string", search: true },
      source: { type: "string", search: true },
      delivery_ticket_reference: { type: "string", search: true },
      delivery_signature_attachment_id: { type: "string", search: true },
      delivery_coordinates: { type: "string", search: true },
      delivery_distance_m: { type: "number" },
      delivery_within_geofence: { type: "boolean" },
      articulo_index: { type: "number" },
      product: { type: "string", search: true },
      product_name: { type: "string", search: true },
      product_code: { type: "string", search: true },
      quantity: { type: "number" },
      notes: { type: "string", search: true },
      delivery_address_coordinates: { type: "string", search: true },
      contenido: { type: "json" },
      last_logistics_event_type: { type: "string", search: true },
      logistics_events: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: entregas_tables,
  pages: entregas_pages,
  menu: [],
});
