import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { delivery_return_pages } from "./delivery-return.pages.ts";
import { delivery_return_tables } from "./delivery-return.tables.ts";

export const delivery_return_module = define_module({
  resource: "delivery-return",
  labels: {
    singular: "Devoluciones",
    plural: "Devoluciones",
    read: "Ver Devoluciones",
    write: "Editar Devoluciones",
  },
  routes: define_crud({
    resource: "delivery-return",
    table: "delivery_return",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "delivery",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      pedido_folio: { type: "string", search: true },
      contacto_nombre: { type: "string", search: true },
      estado: { type: "string", search: true },
      fecha: { type: "string", search: true },
      producto: { type: "string", search: true },
      producto_nombre: { type: "string", search: true },
      producto_codigo: { type: "string", search: true },
      cantidad: { type: "number" },
      motivo: { type: "string", search: true },
      estado_producto: { type: "string", search: true },
      foto_attachment_id: { type: "string", search: true },
      latitude: { type: "number" },
      longitude: { type: "number" },
      pedido: { type: "string", search: true },
      delivery_package: { type: "string", search: true },
      contacto: { type: "string", search: true },
      lineas: { type: "json" },
      firma_conformidad_attachment_id: { type: "string", search: true },
      coordinates: { type: "string", search: true },
      ubicacion_recepcion: { type: "string", search: true },
      ubicacion_recepcion_codigo: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: delivery_return_tables,
  pages: delivery_return_pages,
  menu: [
    {
      id: "logistica.pedidos",
      label: "Pedidos por empacar",
      order: -1,
      pageId: "logistica.pedidos",
      path: "pedidos",
      permission: "subject.logistica.pedidos.read",
      icon: "document",
    },
    {
      id: "logistica.delivery-package",
      label: "Bultos",
      order: 0,
      pageId: "logistica.delivery-package",
      path: "delivery-package",
      permission: "subject.logistica.delivery-package.read",
      icon: "document",
    },
    {
      id: "logistica.delivery-route",
      label: "Rutas de entrega",
      order: 0,
      pageId: "logistica.delivery-route",
      path: "delivery-route",
      permission: "subject.logistica.delivery-route.read",
      icon: "document",
    },
    {
      id: "logistica.delivery-package-manifiesto",
      label: "Manifiesto de carga",
      order: 1,
      pageId: "logistica.delivery-package-manifiesto",
      path: "delivery-package-manifiesto",
      permission: "subject.logistica.delivery-package-manifiesto.read",
      icon: "document",
    },
    {
      id: "logistica.delivery-route-mapa",
      label: "Mapa de rutas",
      order: 2,
      pageId: "logistica.delivery-route-mapa",
      path: "delivery-route-mapa",
      permission: "subject.logistica.delivery-route-mapa.read",
      icon: "document",
    },
    {
      id: "logistica.reparto",
      label: "Reparto (chofer)",
      order: 3,
      pageId: "logistica.reparto",
      path: "reparto",
      permission: "subject.logistica.reparto.read",
      icon: "document",
    },
    {
      id: "logistica.entregas",
      label: "Cola chofer (carga/entrega)",
      order: 4,
      pageId: "logistica.entregas",
      path: "entregas",
      permission: "subject.logistica.entregas.read",
      icon: "document",
    },
    {
      id: "logistica.delivery-return",
      label: "Devoluciones",
      order: 5,
      pageId: "logistica.delivery-return",
      path: "delivery-return",
      permission: "subject.logistica.delivery-return.read",
      icon: "document",
    }
    ],
});
