import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const delivery_return_tables: KirletTableDecl[] = [
  {
    name: "delivery_return",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "pedido_folio", type: "text" },
      { name: "contacto_nombre", type: "text" },
      { name: "estado", type: "text" },
      { name: "fecha", type: "text" },
      { name: "producto", type: "text" },
      { name: "producto_nombre", type: "text" },
      { name: "producto_codigo", type: "text" },
      { name: "cantidad", type: "real" },
      { name: "motivo", type: "text" },
      { name: "estado_producto", type: "text" },
      { name: "foto_attachment_id", type: "text" },
      { name: "latitude", type: "real" },
      { name: "longitude", type: "real" },
      { name: "pedido", type: "text" },
      { name: "delivery_package", type: "text" },
      { name: "contacto", type: "text" },
      { name: "lineas", type: "json" },
      { name: "firma_conformidad_attachment_id", type: "text" },
      { name: "coordinates", type: "text" },
      { name: "ubicacion_recepcion", type: "text" },
      { name: "ubicacion_recepcion_codigo", type: "text" },
    ],
    indexes: [
      { name: "idx_delivery_return_name", columns: ["name"] },
      { name: "idx_delivery_return_active", columns: ["is_active"] },
    ],
  },
];
