import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { delivery_route_mapa_pages } from "./delivery-route-mapa.pages.ts";
import { delivery_route_mapa_tables } from "./delivery-route-mapa.tables.ts";

export const delivery_route_mapa_module = define_module({
  resource: "delivery-route-mapa",
  labels: {
    singular: "Mapa de rutas",
    plural: "Mapa de rutas",
    read: "Ver Mapa de rutas",
    write: "Editar Mapa de rutas",
  },
  routes: define_crud({
    resource: "delivery-route-mapa",
    table: "delivery_route_mapa",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "delivery",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      contacts: { type: "string", search: true },
      vehicle: { type: "string", search: true },
      vehicle_name: { type: "string", search: true },
      pedido: { type: "string", search: true },
      package_ids: { type: "json" },
      latitude: { type: "number" },
      longitude: { type: "number" },
      label: { type: "string", search: true },
      demand_kg: { type: "number" },
      sequence: { type: "number" },
      cumulative_distance_meters: { type: "number" },
      cumulative_duration_seconds: { type: "number" },
      eta: { type: "string", search: true },
      origin_source: { type: "string", search: true },
      ordered_stops: { type: "json" },
      total_distance_meters: { type: "number" },
      total_duration_seconds: { type: "number" },
      encoded_polyline: { type: "string", search: true },
      provider: { type: "string", search: true },
      optimized_at: { type: "string", search: true },
      optimization: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: delivery_route_mapa_tables,
  pages: delivery_route_mapa_pages,
  menu: [],
});
