import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-logistica";

export const delivery_package_manifiesto_pages: KirletPageDecl[] = [
  {
    id: "logistica.delivery-package-manifiesto",
    path: "delivery-package-manifiesto",
    permission: "subject.logistica.delivery-package-manifiesto.read",
    build: () =>
      build_feature_shell_page({
        id: "logistica.delivery-package-manifiesto",
        owner: "subject-logistica",
        title: "Manifiesto de carga",
        props: {
          basePath: "delivery-package-manifiesto",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Manifiesto de carga",
            subtitle: "Submenú de logistica",
            pluralLabel: "manifiesto de carga",
            singularLabel: "manifiesto de carga",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/delivery-package-manifiesto`,
            record: `${API}/delivery-package-manifiesto/:id`,
            create: { method: "POST", action: `${API}/delivery-package-manifiesto` },
            update: { method: "PATCH", action: `${API}/delivery-package-manifiesto/:id` },
            delete: { method: "DELETE", action: `${API}/delivery-package-manifiesto/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "pedido", label: "pedido", sortable: true, priority: 3 },
              { key: "pedido_folio", label: "pedido folio", sortable: true, priority: 3 },
              { key: "pedido_folio_interno", label: "pedido folio interno", sortable: true, priority: 3 },
              { key: "pedido_contacto_nombre", label: "pedido contacto nombre", sortable: true, priority: 3 },
              { key: "pedido_contacto_domicilio", label: "pedido contacto domicilio", sortable: true, priority: 3 },
              { key: "pedido_contacto_url_maps", label: "pedido contacto url maps", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-textarea", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "pedido", component: "input-datalist", label: "pedido", optionsSource: "api://m/subject-ventas/pedidos?as=options&limite=1000" },
              { name: "pedido_folio", component: "input-text", label: "pedido folio" },
              { name: "pedido_folio_interno", component: "input-number", label: "pedido folio interno" },
              { name: "pedido_contacto_nombre", component: "input-text", label: "pedido contacto nombre" },
              { name: "pedido_contacto_domicilio", component: "input-text", label: "pedido contacto domicilio" },
              { name: "pedido_contacto_url_maps", component: "input-text", label: "pedido contacto url maps", type: "url" },
              { name: "delivery_route", component: "input-datalist", label: "delivery route", optionsSource: "api://m/subject-logistica/delivery-route?as=options&limite=1000" },
              { name: "delivery_route_nombre", component: "input-text", label: "delivery route nombre" },
              { name: "vehicle", component: "input-datalist", label: "vehicle", optionsSource: "api://m/subject-vehiculos/vehicle?as=options&limite=1000" },
              { name: "vehicle_nombre", component: "input-text", label: "vehicle nombre" },
              { name: "codigo_bulto", component: "input-text", label: "codigo bulto" },
              { name: "numero_bulto", component: "input-number", label: "numero bulto" },
              { name: "peso_kg", component: "input-number", label: "peso kg" },
              { name: "contenido_resumen", component: "input-textarea", label: "contenido resumen" },
              { name: "pedido_total_bultos", component: "input-number", label: "pedido total bultos" },
              {
                name: "estado",
                component: "input-menu",
                label: "estado",
                options: [
                  { value: "pendiente", label: "Pendiente" },
                  { value: "asignado", label: "Asignado" },
                  { value: "cargado", label: "Cargado" },
                  { value: "en_ruta", label: "En ruta" },
                  { value: "entregado", label: "Entregado" },
                  { value: "incidencia", label: "Incidencia" },
                  { value: "cancelado", label: "Cancelado" },
                ],
              },
              { name: "latitude", component: "input-number", label: "latitude", min: -90, max: 90 },
              { name: "longitude", component: "input-number", label: "longitude", min: -180, max: 180 },
              { name: "event_id", component: "input-text", label: "event id" },
              { name: "event_type", component: "input-text", label: "event type" },
              { name: "source", component: "input-text", label: "source" },
              { name: "delivery_ticket_reference", component: "input-text", label: "delivery ticket reference" },
              { name: "delivery_signature_attachment_id", component: "input-text", label: "delivery signature attachment id" },
              { name: "delivery_coordinates", component: "input-text", label: "delivery coordinates" },
              { name: "delivery_distance_m", component: "input-number", label: "delivery distance m" },
              { name: "delivery_within_geofence", component: "input-checkbox", label: "delivery within geofence" },
              { name: "articulo_index", component: "input-number", label: "articulo index" },
              { name: "product", component: "input-text", label: "product" },
              { name: "product_name", component: "input-text", label: "product name" },
              { name: "product_code", component: "input-text", label: "product code" },
              { name: "quantity", component: "input-number", label: "quantity" },
              { name: "notes", component: "input-textarea", label: "notes" },
              { name: "delivery_address_coordinates", component: "input-text", label: "delivery address coordinates" },
              { name: "contenido", component: "input-json", label: "contenido" },
              { name: "last_logistics_event_type", component: "input-text", label: "last logistics event type" },
              { name: "logistics_events", component: "input-json", label: "logistics events" },
            ],
          },
        },
      }),
  },
];
