import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const pedidos_tables: KirletTableDecl[] = [
  {
    name: "pedidos",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "pedido", type: "text" },
      { name: "pedido_folio", type: "text" },
      { name: "pedido_folio_interno", type: "real" },
      { name: "pedido_contacto_nombre", type: "text" },
      { name: "pedido_contacto_domicilio", type: "text" },
      { name: "pedido_contacto_url_maps", type: "text" },
      { name: "delivery_route", type: "text" },
      { name: "delivery_route_nombre", type: "text" },
      { name: "vehicle", type: "text" },
      { name: "vehicle_nombre", type: "text" },
      { name: "codigo_bulto", type: "text" },
      { name: "numero_bulto", type: "real" },
      { name: "peso_kg", type: "real" },
      { name: "contenido_resumen", type: "text" },
      { name: "pedido_total_bultos", type: "real" },
      { name: "estado", type: "text" },
      { name: "latitude", type: "real" },
      { name: "longitude", type: "real" },
      { name: "event_id", type: "text" },
      { name: "event_type", type: "text" },
      { name: "source", type: "text" },
      { name: "delivery_ticket_reference", type: "text" },
      { name: "delivery_signature_attachment_id", type: "text" },
      { name: "delivery_coordinates", type: "text" },
      { name: "delivery_distance_m", type: "real" },
      { name: "delivery_within_geofence", type: "boolean" },
      { name: "articulo_index", type: "real" },
      { name: "product", type: "text" },
      { name: "product_name", type: "text" },
      { name: "product_code", type: "text" },
      { name: "quantity", type: "real" },
      { name: "notes", type: "text" },
      { name: "delivery_address_coordinates", type: "text" },
      { name: "contenido", type: "json" },
      { name: "last_logistics_event_type", type: "text" },
      { name: "logistics_events", type: "json" },
    ],
    indexes: [
      { name: "idx_pedidos_name", columns: ["name"] },
      { name: "idx_pedidos_active", columns: ["is_active"] },
    ],
  },
];
