import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const delivery_route_tables: KirletTableDecl[] = [
  {
    name: "delivery_route",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "contacts", type: "text" },
      { name: "vehicle", type: "text" },
      { name: "vehicle_name", type: "text" },
      { name: "pedido", type: "text" },
      { name: "package_ids", type: "json" },
      { name: "latitude", type: "real" },
      { name: "longitude", type: "real" },
      { name: "label", type: "text" },
      { name: "demand_kg", type: "real" },
      { name: "sequence", type: "real" },
      { name: "cumulative_distance_meters", type: "real" },
      { name: "cumulative_duration_seconds", type: "real" },
      { name: "eta", type: "text" },
      { name: "origin_source", type: "text" },
      { name: "ordered_stops", type: "json" },
      { name: "total_distance_meters", type: "real" },
      { name: "total_duration_seconds", type: "real" },
      { name: "encoded_polyline", type: "text" },
      { name: "provider", type: "text" },
      { name: "optimized_at", type: "text" },
      { name: "optimization", type: "text" },
    ],
    indexes: [
      { name: "idx_delivery_route_name", columns: ["name"] },
      { name: "idx_delivery_route_active", columns: ["is_active"] },
    ],
  },
];
